<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ink.glowing.text</groupId>
    <artifactId>inkymessage-project</artifactId>
    <version>0.13.0</version>
    <packaging>pom</packaging>
    <modules>
        <module>inkymessage</module>
        <module>extra</module>
        <module>example</module>
    </modules>

    <properties>
        <annotations.version>24.0.1</annotations.version>
        <adventure.version>5.2.0</adventure.version>
        <paper.version>[26.2.build,)</paper.version>
        <java.version>25</java.version>

        <maven.compiler.release>${java.version}</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <extensions>
            <extension>
                <groupId>org.apache.maven.extensions</groupId>
                <artifactId>maven-build-cache-extension</artifactId>
                <version>1.2.3</version>
            </extension>
        </extensions>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.12.0</version>
                <configuration>
                    <links>
                        <link>https://jd.papermc.io/adventure/${adventure.version}/</link>
                        <ling>https://javadoc.io/doc/org.jetbrains/annotations/${annotations.version}/</ling>
                    </links>
                </configuration>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>3.1.4</version>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>${annotations.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-api</artifactId>
            <version>${adventure.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.7.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <distributionManagement>
        <repository>
            <id>glowing-ink</id>
            <url>https://repo.glowing.ink/releases</url>
        </repository>
        <snapshotRepository>
            <id>glowing-ink</id>
            <url>https://repo.glowing.ink/snapshots</url>
        </snapshotRepository>
    </distributionManagement>
</project>